# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgebit" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "53baf15b69e04bc1014f911a532eb742d3c438c7661960fa15f35cc0a775db96"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e17c3079bf7d77de1c5370c25c9bf743c850cc472187ed99e104be398fcef73"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "15d9ff107b818f1c60c3c4323a6d69a43c45589a370e8302fc913aeafacd3490"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "458659cddb2ea02082aad0b7e6f6b8655159fd82fc758e423be19f166076595f"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "forgebit"
  desc "CLI for Forgebit — issue, verify, and manage software licenses from the terminal"
  homepage "https://forgebit.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgebit"

  # No zap stanza required

end
