# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgebit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "398e7f12936ea475f1a5641f6e5b2e2d38f4acc6cc1a2de981a8db4873604737"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c248442f69144f58d01c75c33f20e0ef4ff26908f5cf07e0d093fed8d0ac8d1e"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6895ed362c932c2278f9c3175c1dd498ba338d26af1a6338c93b3a2a101cfc4a"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9a1c49fcac3c24a2506f8fff58c525578afdc15527caa2f2c1c298e2aa5b502"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "forgebit"
  desc "CLI for Forgebit — issue, verify, and manage software licenses from the terminal"
  homepage "https://forgebit.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgebit"

  # No zap stanza required

end
