# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgebit" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a3a7af213cc60e539ffd7d575bd6f818662df5e3f245e80a1c6557182656fd6c"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a5308ad303ec265eccdd1245fc273a28a4b11175a1515a3301c9b25ff81066c"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2e7190353926c2eb5a5f3cd2b9d5b6f5c35ff214e287711344bd852855b7723"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6639071a9b869ace048e78861573d05b8d55803e00681e5c45d3f61908bc4dcb"
      url "https://github.com/boone-studios/forgebit-cli/releases/download/v#{version}/forgebit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "forgebit"
  desc "CLI for Forgebit — issue, verify, and manage software licenses from the terminal"
  homepage "https://forgebit.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgebit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgebit"]
    end
  end

  # No zap stanza required

end
